### ISSUE TITLE
Syntax error when using http-constants

### ISSUE THREAD

**Issue by hubbergit** [aetheric/http-constants#1]
Hi,

just tried to use the useful library. However I get a `SyntaxError: Unexpected token import` in line 4 of index.js, because the import statement is not supported by Node. Seems like you have to use `require` instead.

How do you use the library?

Thanks in advance

**Comment by Tzrlk** [comment]
Hi there, I honestly haven't thought about this library in a while.
Super-annoying that node hasn't supported the module system in ES6, but
that's the shit we eat, I guess.
I'll flip things over to require so it actually works without needing to
run it through a transpiler.

**Comment by Tzrlk** [comment]
Taking another look at it (haven't touched it in ages), wow, I'm not sure what I was doing there. I'll do the quick fix first to get it working, and maybe look at de-shitting it later.

**Comment by Tzrlk** [comment]
Let me know if things are any clearer. I'll have to fix my travis build to get things working properly, however.

**Comment by Tzrlk** [comment]
Whelp, it's deployed to npm. Can you give that a whirl and see how that goes?

**Comment by hubbergit** [comment]
Wow, thanks for the very quick response to the issue!

I created a test file `test.js` with only one statement in it:

`var http_const = require( 'http-constants/target/dist/http-constants.js' );`

When I run that file with

`node test.js`

it fails with the following error message

```
consts.js:96
Object.defineProperties(exports, {
       ^

TypeError: Cannot redefine property: default
    at Function.defineProperties (native)
    at Object.<anonymous> (consts.js:96:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\yahi\new\test.js:3:18)
```

Do you know what the problem is?

May I suggest to write a few simple tests?

Thanks in advance

**Comment by valioDOTch** [comment]
gah
I just realized that I was probably losing lots of time today, because I haven't realized that this is currently WiP.
I just looked for a similar library, as I needed those consts in my Service Worker.
Because I haven't had so much exposure to requireJS and the like I thought this was my fault.

As said I'm anything but an export with this topic, but AFAIK the problem is that the transpiling process seems to concat those JS files wrongly. 

There should be a default export for one object or several named exports.
Currently there are multiple default exports for the various files that were transpiled into that dist-file; but you can have only one default export object in a file; e.g. see
https://stackoverflow.com/questions/39160817/node-modules-issue-only-one-default-export-allowed-per-module

**Comment by Tzrlk** [comment]
I just completely redid the build process, and added a test to make sure the module can be imported. If all went to plan, you _should_ be able to just import the module and have access to all the stuff.

**Comment by hubbergit** [comment]
Works for me now!

Thanks!
